apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-micro
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: node-micro
    spec:
      containers:
      - name: node-micro
        image: idoco/node-micro
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: LOADMILL_VERIFY_TOKEN
          value: f037b345c4c820e59a25ace38fc0b3a1
